  
  CREATE TABLESPACE TS_EDILOJA_DATOS 
  DATAFILE 'C:\app\dbast\product\21c\oradata\XE\ts_ediloja_datos01.dbf' SIZE 100M 
  AUTOEXTEND ON NEXT 20M MAXSIZE 500M
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;
  
  CREATE TABLESPACE TS_EDILOJA_CATALOGOS
  DATAFILE 'C:\app\dbast\product\21c\oradata\XE\ts_ediloja_cat01.dbf' SIZE 30M
  AUTOEXTEND ON NEXT 10M MAXSIZE 100M
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;
  
  CREATE TABLESPACE TS_EDILOJA_HISTORICOS
  DATAFILE 'C:\app\dbast\product\21c\oradata\XE\ts_ediloja_hist01.dbf' SIZE 50M
  AUTOEXTEND ON NEXT 25M MAXSIZE 1G
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TS_EDILOJA_INDICES
  DATAFILE 'C:\app\dbast\product\21c\oradata\XE\ts_ediloja_idx01.dbf' SIZE 50M
  AUTOEXTEND ON NEXT 15M MAXSIZE 300M
  EXTENT MANAGEMENT LOCAL
  SEGMENT SPACE MANAGEMENT AUTO;



  
  
ALTER SESSION SET CONTAINER = XEPDB1;

-- Creación del usuario
CREATE USER Admin_Ediloja IDENTIFIED BY pwdhr;

-- Roles básicos
GRANT CONNECT TO Admin_Ediloja;
GRANT RESOURCE TO Admin_Ediloja;

-- Privilegios de objetos
GRANT CREATE MATERIALIZED VIEW,
      CREATE PROCEDURE,
      CREATE SEQUENCE,
      CREATE SESSION,
      CREATE SYNONYM,
      CREATE TABLE,
      CREATE TRIGGER,
      CREATE TYPE,
      CREATE VIEW
  TO Admin_Ediloja;

-- Tablespace por defecto para objetos del usuario
ALTER USER Admin_Ediloja DEFAULT TABLESPACE TS_EDILOJA_DATOS;

-- Tablespace temporal
ALTER USER Admin_Ediloja TEMPORARY TABLESPACE TEMP;

-- Cuotas en cada tablespace (UNLIMITED para que pueda crear objetos)
ALTER USER Admin_Ediloja QUOTA UNLIMITED ON TS_EDILOJA_DATOS;
ALTER USER Admin_Ediloja QUOTA UNLIMITED ON TS_EDILOJA_CATALOGOS;
ALTER USER Admin_Ediloja QUOTA UNLIMITED ON TS_EDILOJA_HISTORICOS;
ALTER USER Admin_Ediloja QUOTA UNLIMITED ON TS_EDILOJA_INDICES;